# Generated by Django 3.1.3 on 2020-11-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201126_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=255, verbose_name='Ваше ФИО или название'),
        ),
    ]
