# Generated by Django 3.1.3 on 2020-11-27 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20201127_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='opinion',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
