# Generated by Django 3.1.3 on 2020-11-28 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20201127_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='opinion',
            new_name='rating',
        ),
    ]
